  - name: books
    url: https://books.toscrape.com/
    parser: books
    output_format: json

  - name: quotes
    url: https://quotes.toscrape.com/
    parser: quotes
    output_format: json

  - name: quotes_js
    url: http://quotes.toscrape.com/js/
    parser: quotes_splash
    output_format: json
    splash: true
